apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-microservice
  labels:
    app: products-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-microservice
  template:
    metadata:
      labels:
        app: products-microservice
    spec:
      containers:
        - name: products-microservice
          image: juanhoyos/microservice:products-v9
          ports:
            - containerPort: 8086
          env:
            - name: SERVER_PORT
              value: "8086"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: accessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secretAccessKey
            - name: AWS_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: s3Bucket
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
